import { defineComponentStates } from "@/components/types";
import { FIXED_CONTENT, NOT_AN_INPUT, NOT_INTERACTIVE } from "@/components/not-applicable";
import { Icon } from "./Icon";

export const iconStates = defineComponentStates({
  name: "Icon",
  group: "primitives",
  status: "draft",
  flows: [],
  description:
    "The prototype's icon set, drawn on a 20×20 grid and stroked in currentColor. Always decorative: every use pairs an icon with a visible or visually-hidden label.",
  component: Icon,
  notApplicable: {
    ...NOT_INTERACTIVE,
    ...FIXED_CONTENT,
    empty: "Always drawn in full; it takes no content.",
    "long text": "Contains no text.",
    filled: NOT_AN_INPUT,
  },
  variants: [
    { label: "Mobile", props: { name: "mobile" } },
    { label: "Tablet", props: { name: "tablet" } },
    { label: "Web", props: { name: "web" } },
    {
      label: "Hub",
      description: "Four staggered panels: the hub of every page in the prototype.",
      props: { name: "hub" },
    },
    { label: "Chevron", props: { name: "chevron" } },
    { label: "Plus", props: { name: "plus" } },
    { label: "Minus", props: { name: "minus" } },
    {
      label: "Contrast",
      description: "The colour switch in the dock: half the disc filled.",
      props: { name: "contrast" },
    },
    {
      label: "Shield",
      description: "Privacy. Closed, because the promise is that nothing leaves.",
      props: { name: "shield" },
    },
    { label: "Lock", props: { name: "lock" } },
    { label: "Mic", props: { name: "mic" } },
    { label: "Send", props: { name: "send" } },
    { label: "Check", props: { name: "check" } },
    { label: "Document", props: { name: "document" } },
    { label: "Link", props: { name: "link" } },
    { label: "Pencil", props: { name: "pencil" } },
    { label: "Attach", props: { name: "attach" } },
    { label: "Home", props: { name: "home" } },
    {
      label: "Calendar",
      description: "Room in the lower half for a date set over it, as the tab bar does for Briefing.",
      props: { name: "calendar" },
    },
    { label: "Person", props: { name: "person" } },
    { label: "Menu", props: { name: "menu" } },
    { label: "Sidebar", description: "Widening or folding a sidebar.", props: { name: "sidebar" } },
    { label: "Close", props: { name: "close" } },
    {
      label: "Draft",
      description: "The pencil with a line under it, as if mid-writing: a draft is open.",
      props: { name: "draft" },
    },
    {
      label: "Reset",
      description: "Puts the prototype's snapshots back as they started. Dock only.",
      props: { name: "reset" },
    },
    {
      label: "Flag",
      description: "A destination: where the plan is headed.",
      props: { name: "flag" },
    },
    { label: "Globe", description: "A personal website.", props: { name: "globe" } },
    { label: "LinkedIn", description: "Drawn, not the brand mark.", props: { name: "linkedin" } },
    { label: "Bell", description: "Follow-ups by email.", props: { name: "bell" } },
    { label: "Download", props: { name: "download" } },
    { label: "Trash", props: { name: "trash" } },
    { label: "Sign out", props: { name: "sign-out" } },
    { label: "Compass", description: "Her direction.", props: { name: "compass" } },
    { label: "Mail", props: { name: "mail" } },
    { label: "Briefing", description: "The Daily Briefing.", props: { name: "briefing" } },
    { label: "Spark", description: "Something has moved, and is worth a note.", props: { name: "spark" } },
    { label: "Large — 32px", props: { name: "web", size: 32 } },
    { label: "Small — 14px", props: { name: "mobile", size: 14 } },
  ],
});
